### ISSUE TITLE
Retort does not Honor User Silences

### ISSUE THREAD

**Issue by hon1nbo** [gdpelican/retort#57]
Retort does not honor the silenced status of users, allowing them to keep using the plugin to react and insult users during a posting ban.

**Comment by gdpelican** [comment]
Good catch; this should now be fixed in the latest.

**Comment by hon1nbo** [comment]
This isn't fixed; updated and still there, I looked at the commit and it seems it's checking suspensions rather than silences. Suspensions shouldn't be a problem since users can't login in the first place, but silenced users can.
